version: 2
sources:
  - name: muneeb_test
    description: "Description of your_source."
    tables:
      - name: customers
      - name: sellers
      - name: products
      - name: product_translations
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews